#!/usr/bin/env bash
#
# Aurora Dashboard — one-shot deploy helper.
#
# Flow: ask how to expose the service → write a .env that drives docker-compose's
# host-side port binding → (optionally) build & start the container → health-check
# it → print the access URL. Defaults to a LOCAL-ONLY deploy.
#
# The whole app is a single container (FastAPI serves the built frontend + /api).
# There are NO server-side secrets — IMAP/AI credentials live in the browser — so
# the generated .env only ever carries networking (bind IP + host port). That's
# why the env we create depends only on the exposure mode you pick below.
#
# Non-interactive use (CI / re-runs): preset any of these and the matching prompt
# is skipped —
#   AURORA_BIND_MODE  = local | tailscale | lan
#   AURORA_HOST_PORT  = 5174
#   AURORA_AUTO_START = yes | no
#
set -euo pipefail

cd "$(dirname "$0")/.."          # repo root
ROOT="$(pwd)"
ENV_FILE="$ROOT/.env"

# ── pretty output ────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  B=$'\033[1m'; DIM=$'\033[2m'; G=$'\033[32m'; Y=$'\033[33m'; R=$'\033[31m'; C=$'\033[36m'; N=$'\033[0m'
else
  B=; DIM=; G=; Y=; R=; C=; N=
fi
say()  { printf '%s\n' "$*"; }
ok()   { printf '%s✓%s %s\n' "$G" "$N" "$*"; }
warn() { printf '%s!%s %s\n' "$Y" "$N" "$*"; }
die()  { printf '%s✗ %s%s\n' "$R" "$*" "$N" >&2; exit 1; }
# ask "prompt" "default" -> echoes the answer (prompt goes to stderr via read -p).
ask() {
  local p="$1" d="${2-}" a
  if [ -n "$d" ]; then read -r -p "$p [$d]: " a || true; printf '%s' "${a:-$d}"
  else read -r -p "$p: " a || true; printf '%s' "$a"; fi
}

say "${B}Aurora Dashboard 部署${N}"

# ── prerequisites ─────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "未找到 docker，请先安装并启动 Docker Desktop。"
if docker compose version >/dev/null 2>&1; then COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then COMPOSE=(docker-compose)
else die "未找到 docker compose（v2 插件或 docker-compose）。"; fi
docker info >/dev/null 2>&1 || die "Docker 守护进程未运行，请先启动 Docker Desktop。"

# ── tailscale helpers ─────────────────────────────────────────────────────────
ts_bin() {
  if command -v tailscale >/dev/null 2>&1; then printf 'tailscale'; return 0; fi
  local app="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
  [ -x "$app" ] && { printf '%s' "$app"; return 0; }
  return 1
}
tailscale_ip() {
  local ts; ts="$(ts_bin)" || return 1
  "$ts" ip -4 2>/dev/null | head -n1
}

# ── 1. exposure mode ──────────────────────────────────────────────────────────
MODE="${AURORA_BIND_MODE:-}"
if [ -z "$MODE" ]; then
  say ""
  say "${B}如何暴露 Aurora？${N}"
  say "  ${B}1${N}) 仅本机        绑定 127.0.0.1，只有这台机器能访问 ${DIM}(默认)${N}"
  say "  ${B}2${N}) 仅 Tailscale  绑定本机 Tailscale IP，只有你的 tailnet 设备能访问"
  say "  ${B}3${N}) 局域网 / 全部 绑定 0.0.0.0，同网段任何设备都能访问 ${Y}(注意安全)${N}"
  case "$(ask "选择" "1")" in
    1) MODE=local ;; 2) MODE=tailscale ;; 3) MODE=lan ;;
    *) die "无效选择。" ;;
  esac
fi

# Resolve the host bind IP from the chosen mode.
case "$MODE" in
  local) BIND_IP="127.0.0.1" ;;
  lan)   BIND_IP="0.0.0.0" ;;
  tailscale)
    BIND_IP="$(tailscale_ip || true)"
    [ -n "$BIND_IP" ] || die "未检测到 Tailscale IP。请确认已安装并 'tailscale up' 登录，或把 Tailscale.app 装在 /Applications。"
    ok "检测到 Tailscale IP：${B}$BIND_IP${N}"
    ;;
  *) die "未知模式：$MODE" ;;
esac

# ── 2. host port ──────────────────────────────────────────────────────────────
PORT="${AURORA_HOST_PORT:-}"
[ -n "$PORT" ] || PORT="$(ask "主机端口" "5174")"
[[ "$PORT" =~ ^[0-9]+$ ]] || die "端口必须是数字：$PORT"

# ── 3. write .env (only the networking vars the chosen mode needs) ────────────
{
  echo "# Generated by scripts/deploy.sh — host-side networking for docker-compose."
  echo "# Exposure mode: $MODE"
  echo "AURORA_BIND_IP=$BIND_IP"
  echo "AURORA_HOST_PORT=$PORT"
} > "$ENV_FILE"
ok "已写入 ${B}$ENV_FILE${N}  (AURORA_BIND_IP=$BIND_IP, AURORA_HOST_PORT=$PORT)"

# ── 4. start now? ─────────────────────────────────────────────────────────────
START="${AURORA_AUTO_START:-}"
if [ -z "$START" ]; then
  case "$(ask "现在构建并启动后端容器？(y/n)" "y")" in
    y|Y|yes) START=yes ;; *) START=no ;;
  esac
fi
if [ "$START" != "yes" ]; then
  say ""
  ok ".env 已就绪，稍后手动启动："
  say "    ${C}${COMPOSE[*]} up -d --build${N}"
  exit 0
fi

# ── 5. build & up ─────────────────────────────────────────────────────────────
say ""
say "${B}构建并启动容器…${N}"
"${COMPOSE[@]}" up -d --build

# ── 6. health check ───────────────────────────────────────────────────────────
# Probe from this machine: 0.0.0.0 isn't a connect target, so probe loopback;
# for tailscale we probe the 100.x address (the host can reach its own tailnet IP).
PROBE_IP="$BIND_IP"; [ "$BIND_IP" = "0.0.0.0" ] && PROBE_IP="127.0.0.1"
HEALTH_URL="http://$PROBE_IP:$PORT/api/health"
say ""
printf '健康检查 %s ' "$HEALTH_URL"
HEALTHY=no
for _ in $(seq 1 30); do
  if curl -fsS --max-time 2 "$HEALTH_URL" >/dev/null 2>&1; then HEALTHY=yes; break; fi
  printf '.'; sleep 2
done
echo

# ── 7. report ─────────────────────────────────────────────────────────────────
say ""
if [ "$HEALTHY" = yes ]; then
  ok "服务健康，部署完成。"
else
  warn "健康检查超时（容器可能仍在启动）。查看日志：${C}${COMPOSE[*]} logs -f${N}"
fi

say ""
say "${B}访问地址${N}"
case "$MODE" in
  local)
    say "  本机：     ${C}http://127.0.0.1:$PORT/${N}"
    ;;
  tailscale)
    say "  Tailnet：  ${C}http://$BIND_IP:$PORT/${N}   ${DIM}(任意已登录同一 tailnet 的设备)${N}"
    say ""
    say "${DIM}说明：100.x 地址只在你的 tailnet 内可路由——没连 Tailscale 的设备（局域网邻居、公网）都没有到达它的路由，正符合“只有 Tailscale 进来才访问得到”。重启后该 IP 不变。${N}"
    say "${DIM}若 Docker Desktop 绑不了该 IP（健康检查一直失败）：把 .env 的 AURORA_BIND_IP 改回 127.0.0.1 重跑本脚本，再执行  ${C}$(ts_bin 2>/dev/null || echo tailscale) serve --bg $PORT${N}${DIM}  —— 同样只在 tailnet 内可达，且自动 HTTPS + MagicDNS 域名。${N}"
    ;;
  lan)
    say "  局域网：   ${C}http://<本机局域网IP>:$PORT/${N}   ${DIM}(同网段任意设备)${N}"
    say "${DIM}提醒：实例未鉴权，不要把这个端口转发/暴露到公网。${N}"
    ;;
esac
